name: mlflow-ci-env  # Name of the conda environment

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - mlflow=1.19.0  # MLflow version
  - scikit-learn=0.24.2  # For ML model training
  - numpy=1.20.3
  - pandas=1.2.4
  - matplotlib=3.4.2
  - pip:
      - pytest==6.2.3  # Optional: if you want to run tests
