name: mlflow-ci-env  # Name of the conda environment

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - mlflow  # MLflow version
  - scikit-learn  # For ML model training
  - numpy
  - pandas
  - matplotlib
  - pip:
      - pytest  # Optional: if you want to run tests
