FROM python:3.10-slim

WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Upgrade pip 
RUN pip install --upgrade pip

# Install dependencies
RUN pip install -r requirements.txt

EXPOSE 8501


CMD ["streamlit","run", "app.py"]