name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering via GitHub UI

jobs:
  mlflow-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 1: Set up Conda environment using conda.yaml
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        conda-version: "4.10.3"  # Use a compatible version of Conda
        environment-file: conda.yaml  # Use conda.yaml to create environment
        auto-activate-base: false  # Don't automatically activate the base environment

    # Step 2: Install dependencies from conda.yaml
    - name: Install dependencies from Conda
      run: |
        conda env create -f conda.yaml  # Create conda environment from conda.yaml
        conda activate mlflow-ci-env  # Activate the created environment
        conda list  # Verify installed packages

    # Step 3: Run MLflow Project
    - name: Run MLflow Project
      run: |
        conda activate mlflow-ci-env  # Ensure the environment is activated
        mlflow run .  # Run MLflow project with parameters

    # Step 4: Run tests (optional)
    # - name: Run tests (optional)
    #   run: |
    #     conda activate mlflow-ci-env  # Ensure environment is activated
    #     pytest tests  # Run tests in the "tests" directory

    # Step 5: Archive the results (optional)
    # - name: Archive MLflow run results (optional)
    #   run: |
    #     mkdir -p mlflow-artifacts
    #     cp -r mlruns ./mlflow-artifacts
