name: CI/CD Pipeline for Disease Symptom Prediction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  mlflow-job:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Install Python 3.8 manually (if necessary)
    - name: Install Python 3.8 manually
      run: |
        sudo apt-get update
        sudo apt-get install python3.8 python3.8-dev python3.8-distutils python3.8-venv python3-pip
        python3.8 --version
        python3 -m pip install --upgrade pip

    # Step 2: Install Miniconda (if necessary)
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        conda-version: "4.9.2"  # Use a stable Conda version (e.g., 4.9.x)
        environment-file: conda.yaml  # Use conda.yaml to create environment
        auto-activate-base: false  # Don't automatically activate the base environment

    # Step 3: Install dependencies from conda.yaml
    - name: Install dependencies with Conda
      run: |
        conda env create -f conda.yaml  # Create conda environment from conda.yaml
        conda activate disease-symptom-prediction-env  # Activate the created environment
        conda list  # Verify installed packages

    # Step 4: Run MLflow project
    - name: Run MLflow Project
      run: |
        conda activate disease-symptom-prediction-env  # Activate the environment
        mlflow run .  # Run the MLflow project

    # Step 5: (Optional) Run tests
    - name: Run tests (optional)
      run: |
        conda activate disease-symptom-prediction-env
        pytest tests  # If you have tests in a "tests" directory

    # Step 6: Archive results (optional)
    - name: Archive MLflow run results
      run: |
        mkdir -p mlflow-artifacts
        cp -r mlruns ./mlflow-artifacts
