name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering via GitHub UI

jobs:
  mlflow-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assumes you have a requirements.txt file

    - name: Install MLflow
      run: pip install mlflow  # Install MLflow locally (you can also use `pip install git+https://github.com/mlflow/mlflow` for the latest)

    - name: Run MLflow Project
      run: |
        # Start MLflow server if needed (optional)
        mlflow server --host 0.0.0.0 --port 5000 &
        
        # Run your MLflow project or MLflow script
        mlflow run . 






    # Step 2: Install dependencies from conda.yaml
    - name: Install dependencies with Conda
      run: |
        conda env create -f conda.yaml  # Create conda environment from conda.yaml
        conda activate mlflow-ci-env  # Activate the created environment

    # Step 3: Run MLflow project
    - name: Run MLflow Project
      run: |
        conda activate mlflow-ci-env  # Ensure the environment is activated
        mlflow run . -P alpha=0.1 -P l1_ratio=0.7  # Run MLflow project with parameters

    # Step 4: Run tests (optional)
    - name: Run tests (optional)
      run: |
        conda activate mlflow-ci-env
        pytest tests  # Run tests in the "tests" directory

    # Step 5: Archive the results (optional)
    - name: Archive MLflow run results (optional)
      run: |
        mkdir -p mlflow-artifacts
        cp -r mlruns ./mlflow-artifacts


